version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
     - db_data:/var/lib/mysql:Z
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: magento
    networks:
     - msite
  # Magento
  magento:
    depends_on: 
     - db
    image: magento
    restart: always
    ports:
     - '8000:80'
    tty: true
    volumes:
     - ./magento-files:/var/www/html:Z
    networks:
     - msite
  #PhpMyAdmin
  phpmyadmin:
    depends_on:
     - db
    image: phpmyadmin/phpmyadmin
    ports:
     - '1234:80'
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: letmein
    networks:
     - msite
networks:
  msite:
volumes:
  db_data:
